// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportCsv() {
  return window['go']['main']['App']['ImportCsv']();
}

export function WriteModel(arg1) {
  return window['go']['main']['App']['WriteModel'](arg1);
}

export function WriteSchema(arg1) {
  return window['go']['main']['App']['WriteSchema'](arg1);
}
