// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function ExportCsvModel(arg1:entity.JsonSchema,arg2:entity.CsvModel):Promise<void>;

export function ExportSchema(arg1:entity.JsonSchema):Promise<void>;

export function ImportCsvData():Promise<entity.CsvData>;

export function ImportSchema():Promise<entity.JsonSchema>;
