// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {core} from '../models';

export function ExitProgram():Promise<void>;

export function ExportJsonSchema(arg1:entity.JsonSchema):Promise<void>;

export function ImportCsvFileData():Promise<entity.CsvFileData>;

export function ImportJsonSchema():Promise<core.ImportSchemaRes>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function ProcessCsvWithSchema(arg1:entity.CsvFileData,arg2:entity.JsonSchema):Promise<entity.CsvProcessingReport>;

export function UnmaximizeWindow():Promise<void>;
