// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ImportCsv():Promise<main.SelectFileRes>;

export function WriteModel(arg1:main.Model):Promise<void>;

export function WriteSchema(arg1:main.Schema):Promise<void>;
