// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCsvModel(arg1, arg2) {
  return window['go']['main']['App']['ExportCsvModel'](arg1, arg2);
}

export function ExportSchema(arg1) {
  return window['go']['main']['App']['ExportSchema'](arg1);
}

export function ImportCsvData() {
  return window['go']['main']['App']['ImportCsvData']();
}

export function ImportSchema() {
  return window['go']['main']['App']['ImportSchema']();
}
