// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportModel(arg1) {
  return window['go']['main']['App']['ExportModel'](arg1);
}

export function ExportSchema(arg1) {
  return window['go']['main']['App']['ExportSchema'](arg1);
}

export function ImportCsvData() {
  return window['go']['main']['App']['ImportCsvData']();
}

export function ImportModel() {
  return window['go']['main']['App']['ImportModel']();
}

export function ImportSchema() {
  return window['go']['main']['App']['ImportSchema']();
}

export function ProcessCsvDescriptor(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessCsvDescriptor'](arg1, arg2, arg3);
}
